### ISSUE TITLE
Compressor Code

### ISSUE THREAD

**Issue by tricktrap** [RAR1741/RA19_RobotCode#11]
It's becoming pretty clear that we'll need an onboard compressor for our pneumatic systems. WPILib has provided a simple Compressor class in the past that took care of managing a compressor by turning it on if the pressure in the tank ever fell below 120 PSI.

We should add that class to our robot code. Look, I'm linking the documentation! http://first.wpi.edu/FRC/roborio/release/docs/java/edu/wpi/first/wpilibj/Compressor.html

We need to do a couple of things:
1. Add an instance of this class to the robot class.
2. Initialize it in robotInit (probably)

**Comment by dracco1993** [comment]
Closed in #14
